### ISSUE TITLE
Unable to Fetch Machine Details 

### ISSUE THREAD

**Issue by suji248** [Gurobi/instantcloud-dotnet#3]
Hello

After the new version of Gurobi 7.0 release  I have found some  problems while using this instantcloud-dotnet. 

1) I have changed the URL by adding v2/machines , v2/licenses ...

When I execute the command am returned output as []  .  jsonStr is returning some values but after that its not giving the License Details.  same thing happens with GetMachines() method

 public License[] GetLicenses()
        {
            Dictionary<string, string> paramDict = new Dictionary<string, string>();
            string jsonStr = SendCommand("licenses", paramDict);
            var serializer = new DataContractJsonSerializer(typeof(License[]));
            License[] licenses = null;
            using (var tempStream = new MemoryStream(Encoding.UTF8.GetBytes(jsonStr)))
            {
                licenses = (License[])serializer.ReadObject(tempStream);
            }
           
            return licenses;

**Comment by gglockner** [comment]
This repository is deprecated. Please upgrade to the new instant cloud API from Gurobi Optimizer 7.0.
